HUMANIZED_PARAS = {}

# Front matter
HUMANIZED_PARAS[21] = 'Monica Gyamfuah (Index: __________) | Signature: ______________ | Date: _________'
HUMANIZED_PARAS[22] = 'Abubakari Rafiatu (Index: __________) | Signature: ______________ | Date: _________'
HUMANIZED_PARAS[23] = 'Owusu Emmanuel (Index: __________) | Signature: ______________ | Date: _________'
HUMANIZED_PARAS[24] = 'Agyekum Isaac (Index: __________) | Signature: ______________ | Date: _________'
HUMANIZED_PARAS[25] = 'Asare Solomon William (Index: __________) | Signature: ______________ | Date: _________'
HUMANIZED_PARAS[27] = 'I hereby declare that the preparation and presentation of this project report were supervised by me in accordance with the guidelines on supervision of project work laid down by the University of Energy and Natural Resources (UENR).'
HUMANIZED_PARAS[31] = 'We dedicate this project to Almighty God for His continuous grace, direction, and strength throughout our studies. We also dedicate this work to our parents, guardians, and families for their unfailing love, prayers, and financial sacrifices. Special thanks go to our lecturers and project supervisor in the Department of Information Technology and Decision Sciences, whose guidance kept us on track. Finally, we dedicate this to our fellow students and friends who shared the late nights and challenges of this work.'
HUMANIZED_PARAS[34] = 'We give sincere thanks to the Almighty God for granting us good health, wisdom, and perseverance to complete this degree project. We express our deepest appreciation to our project supervisor, Dr. Samuel O. Frimpong. His practical advice, rigorous critique, and technical direction guided every stage of this work. We are equally grateful to the University of Energy and Natural Resources (UENR) for providing laboratory space and solar testing resources. We also thank Mr. Joshua A. Weyori for his practical support during documentation and testing. Finally, our appreciation goes to the faculty and staff of the Department of Information Technology and Decision Sciences for their constructive input during our review seminars.'
HUMANIZED_PARAS[37] = 'Solar energy is vital for Ghana\'s renewable electricity targets. Yet, solar panels operating in the field face tough operating conditions. High temperatures, Harmattan dust, and physical stresses damage silicon wafers over time. Common faults such as micro-cracks, surface dirt, and hotspots cut electrical output significantly. When left unattended, these defects cause localized burnouts and fire hazards, costing solar operators substantial revenue every year (IRENA, 2024). To solve this problem, we developed SOLAR SCAN, an edge-based diagnostic inspection system built for offline field work. We fine-tuned a lightweight YOLOv8 object detection model (Jocher et al., 2023) on real-world panel fault datasets and converted it to an INT8 quantized TensorFlow Lite (TFLite) format (TensorFlow Lite, 2024). To prevent false alarms from stray photos, we implemented a two-layer validation gatekeeper: a background COCO filter removes everyday objects, while colour-space histograms filter out vegetation and plain backgrounds. Once cleared, a wafer thermodynamics engine uses Nominal Operating Cell Temperature (NOCT) equations (Duffie & Beckman, 2013) to calculate actual operating temperatures and wattage losses from field irradiance readings. The final 3.2 MB quantized model achieves 92.7% mean Average Precision (mAP@50) with sub-150ms inference latency on standard mobile processors. Field usability testing with 12 technicians and engineering students produced a System Usability Scale (SUS) score of 84.3 out of 100 (Brooke, 1996), proving strong practical utility for solar plant maintenance.'
HUMANIZED_PARAS[38] = 'Keywords: photovoltaic systems, YOLOv8, TensorFlow Lite, edge computing, INT8 quantization, double-layer validation, wafer thermodynamics, NOCT modelling, system usability scale'

# Table & Figure Titles
HUMANIZED_PARAS[47] = 'Table 4.1: YOLOv8 Model Training Performance: Per-Class Precision, Recall and mAP@50'
HUMANIZED_PARAS[50] = 'Table 4.4: Comparative Analysis of Edge Inference Speed (Float32 vs INT8 Quantized)'
HUMANIZED_PARAS[53] = 'Figure 4.1: SOLAR SCAN Diagnostic Scan Lab: Light Studio Interface Mode'
HUMANIZED_PARAS[54] = 'Figure 4.2: SOLAR SCAN Diagnostic Scan Lab: True OLED Pitch Black Dark Mode'
HUMANIZED_PARAS[55] = 'Figure 4.3: Autonomous Drone Inspection GIS Module: Light Studio Mode'
HUMANIZED_PARAS[56] = 'Figure 4.4: Autonomous Drone Inspection GIS Module: True OLED Pitch Black Dark Mode'
HUMANIZED_PARAS[57] = 'Figure 4.5: Fleet Analytics & Defect Distribution Telemetry: Light Studio Mode'
HUMANIZED_PARAS[58] = 'Figure 4.6: Fleet Analytics & Defect Distribution Telemetry: True OLED Pitch Black Dark Mode'
HUMANIZED_PARAS[59] = 'Figure 4.7: Evidence Hub & Normalized 9x9 Confusion Matrix: Light Studio Mode'
HUMANIZED_PARAS[60] = 'Figure 4.8: Evidence Hub & Normalized 9x9 Confusion Matrix: True OLED Pitch Black Dark Mode'

# Chapter 1
HUMANIZED_PARAS[64] = 'Solar energy installations have expanded rapidly across Ghana over the past ten years. What began as scattered pilot projects is now a core part of the national electrification plan. Large arrays, like the Bui Power Authority solar farm, feed power into the municipal grid and supply remote communities in the Bono region. Still, keeping these facilities running at peak output requires constant maintenance. Solar panels sit outdoors under harsh weather for decades. Sensitive silicon cells must withstand intense ultraviolet exposure, seasonal rainfall, and high operating temperatures.'
HUMANIZED_PARAS[65] = 'Field conditions take a heavy toll on solar hardware. Modules face constant mechanical stress from wind gusts, ambient temperature swings, soot deposits, and bird droppings. These stresses cause cell cracking, solder bond fatigue, and encapsulant aging. Among the most frequent faults are micro-cracks, dust layers, hotspots, bypass diode failures, delamination, snail trails, and potential induced degradation (Luo et al., 2021). If field teams do not catch these faults early, reverse-bias current can overheat damaged cells. Temperatures often climb past 80°C, melting protective backsheets and destroying entire strings of panels.'
HUMANIZED_PARAS[66] = 'In Ghana, local weather makes these degradation issues even worse. During the Harmattan season, desert dust carried from the Sahara settles on panel glass, blocking sunlight and cutting electrical yields drastically. High relative humidity in southern districts accelerates moisture penetration, promoting corrosion and voltage leakage. Meanwhile, ambient temperatures frequently exceed 35°C in Sunyani and northern districts, raising baseline cell temperatures and worsening hotspot damage. Researchers at the University of Energy and Natural Resources (UENR) have pointed out that solar maintenance teams in Ghana need practical digital tools that work right in the field.'
HUMANIZED_PARAS[67] = 'To keep panels generating power for their full 25-year design life, technicians must inspect arrays regularly. In the past, technicians walked through arrays on foot, holding thermal infrared cameras or checking panels by hand. That process works fine for small residential rooftops. On a utility solar farm with fifty thousand panels, however, walking the rows takes weeks of tiring physical work. By the time technicians finish a single pass, hidden faults have already caused major energy losses.'
HUMANIZED_PARAS[68] = 'Using camera-equipped drones has helped speed up inspection routines. Drones can sweep through large solar farms in hours, collecting thousands of aerial photographs and thermal maps. But this creates another bottleneck. Field engineers must spend days manually reviewing thousands of images on a computer screen. Machine learning models offer a way to automate this detection process. The challenge is that standard AI tools depend on cloud APIs, which need fast internet. That creates a major roadblock in rural Ghana, where mobile internet is patchy or completely unavailable.'
HUMANIZED_PARAS[69] = 'Running computer vision models directly on mobile phones solves the connectivity issue, but mobile hardware has strict computing limits. Standard object detection networks, like Faster R-CNN or full-sized PyTorch YOLO models, require heavy graphics memory and quickly drain phone batteries. A technician in the field needs an app that runs smoothly on everyday Android and iOS smartphones. To make that possible, we used post-training INT8 integer quantization (TensorFlow Lite, 2024), pruning model weights down to 3.2 MB so inference runs quickly on standard phone processors.'
HUMANIZED_PARAS[70] = 'Operating in the field also brings messy real-world data. Technicians often upload blurry snapshots, misaligned frames, or accidental photos of surrounding grass, dirt tracks, and vehicles. Running deep neural networks on invalid images wastes battery power and generates confusing false alarms. To prevent this, an edge diagnostic tool needs an automated validation gatekeeper that filters uploads before running the main AI pipeline. Pairing computer vision with real-world thermodynamic equations gives field technicians an offline inspection utility that turns panel photos into direct, actionable repair decisions.'
HUMANIZED_PARAS[72] = 'Utility-scale and mini-grid solar installations in Ghana are usually located in remote rural districts with little or no cellular network coverage. Because of this, inspection workflows that rely on cloud servers fail completely at the job site. Field crews must record pictures on site, carry their devices back to town, and run analysis days later. That delay prevents prompt fixes for critical faults like hotspots, which can cause permanent burnouts within hours of peak sunlight. There is an urgent need for an offline-first tool that runs full AI inference right on a technician\'s handheld phone at the solar array.'
HUMANIZED_PARAS[73] = 'Another major weakness in current inspection apps is the absence of input validation. When technicians work quickly in the field, they often capture photos containing ground vegetation, bare dirt, fences, or harsh shadows. Standard neural networks still attempt to draw bounding boxes on these non-solar images, producing false alarms that confuse maintenance crews and waste battery power. A practical mobile application must include a built-in gatekeeper that checks colour distributions and texture gradients, blocking non-solar uploads before they trigger inference.'
HUMANIZED_PARAS[74] = 'Standard computer vision models output only raw bounding boxes and confidence percentages, which tell technicians very little about actual panel health. In the field, an operator needs to know how much electricity a panel is losing and how hot it is getting. An abstract confidence score does not tell a manager whether to wash a dirty panel immediately or replace a cracked module next week. Without converting visual findings into physical metrics like temperature rise and lost wattage, maintenance teams cannot plan their work effectively.'
HUMANIZED_PARAS[75] = 'Industrial thermal cameras and proprietary diagnostic software are also far too expensive for local solar operators in developing economies. High licensing and equipment fees force local teams to rely on basic visual checks, leading to unspotted defects and shortened panel lifespans. Developing a low-cost, open software platform that runs on consumer smartphones using compressed neural networks makes advanced diagnostics accessible to local technicians and supports clean energy growth across Ghana.'
HUMANIZED_PARAS[77] = 'To address these operational hurdles, this study investigates five core engineering questions:'
HUMANIZED_PARAS[78] = 'Which neural network architecture delivers the best trade-off between detection accuracy (mAP) and execution speed when deployed on mobile edge processors for solar fault detection?'
HUMANIZED_PARAS[79] = 'How effectively does post-training INT8 integer quantization (TensorFlow Lite, 2024) shrink custom YOLOv8 models for mobile deployment without causing major accuracy drops?'
HUMANIZED_PARAS[80] = 'What combination of object filters and colour-gradient checks creates a reliable gatekeeper that filters out background noise under field conditions?'
HUMANIZED_PARAS[81] = 'How can Nominal Operating Cell Temperature (NOCT) equations (Duffie & Beckman, 2013) be combined with visual detection confidence to estimate real cell operating temperatures and wattage losses?'
HUMANIZED_PARAS[82] = 'How well does an offline-first mobile diagnostic interface support the everyday workflow of field solar technicians, based on System Usability Scale (SUS) metrics (Brooke, 1996)?'
HUMANIZED_PARAS[84] = 'This study delivers practical benefits across technical, economic, and educational domains. Solar power installations are expanding, but keeping them productive over decades requires accessible maintenance tools. In resource-constrained settings like Ghana, our system turns standard smartphones into reliable diagnostic devices, removing the need for costly imported thermal cameras.'
HUMANIZED_PARAS[85] = 'From an economic standpoint, prompt defect detection protects solar farm revenue. Catching micro-cracks and hot spots before they destroy panel strings reduces equipment replacement expenses. Our thermodynamics engine converts visual bounding boxes into lost wattage, helping solar farm managers justify repair schedules with concrete financial figures.'
HUMANIZED_PARAS[86] = 'Academically, this project contributes practical data on deploying compressed neural networks at the edge. We show that INT8 quantization can compress models down to 3.2 MB while preserving diagnostic precision on real-world solar datasets. The two-layer validation gatekeeper also demonstrates a lightweight way to guard mobile AI apps against out-of-domain inputs and unnecessary battery drain.'
HUMANIZED_PARAS[87] = 'Finally, this work supports the clean energy and digitalization goals of the University of Energy and Natural Resources (UENR). By combining machine learning with renewable energy engineering, this project provides a working model for student researchers and local engineers tackling infrastructure challenges in Ghana.'
HUMANIZED_PARAS[89] = 'This study covers the development, optimization, and field evaluation of the SOLAR SCAN diagnostic system. Our custom YOLOv8 model detects nine common fault categories: hotspots, micro-cracks, soiling, bypass diode failures, delamination, cell discoloration, snail trails, potential induced degradation (PID), and snow cover. The project uses visual RGB photos, drone thermal infrared images, and electroluminescence scans. The mobile software runs offline as a Progressive Web Application (PWA) on Android and iOS devices, with cloud API failover when an internet connection is available.'
HUMANIZED_PARAS[92] = 'The general objective of this project is to design, develop, and evaluate an automated, edge-deployed mobile diagnostic system, named SOLAR SCAN, for the offline detection, classification, and physical characterization of photovoltaic panel defects. The system combines an optimized YOLOv8 neural network with TensorFlow Lite (TFLite) mobile execution, providing solar technicians in Ghana with a fast, low-cost inspection tool that functions without continuous internet access.'
HUMANIZED_PARAS[94] = 'To accomplish the general objective, we set out the following three specific objectives:'
HUMANIZED_PARAS[95] = '1. To curate an annotated multi-modal dataset (visual RGB, thermal infrared, and electroluminescence) and train a custom YOLOv8 object detection model, applying post-training INT8 quantization to compress model weights from 6.3 MB to 3.2 MB for rapid, offline edge inference on mobile CPUs.'
HUMANIZED_PARAS[96] = '2. To design and implement the SOLAR SCAN software architecture integrating a client-side Double-Layer Validation Gatekeeper to prevent out-of-domain false inferences, coupled with a dynamic wafer thermodynamics engine that calculates cell operating temperatures and real wattage losses via NOCT physical modeling.'
HUMANIZED_PARAS[97] = '3. To empirically evaluate the diagnostic accuracy, inference latency, and field usability of the complete system using benchmark detection metrics (precision, recall, mAP) alongside standardized System Usability Scale (SUS) assessments with clean energy technicians in Ghana.'
HUMANIZED_PARAS[100] = 'This documentation is organized into five main chapters. Chapter 1 introduces the project background, problem statement, research questions, objectives, significance, and scope. Chapter 2 reviews the literature on photovoltaic cell physics, defect types, inspection methods, deep learning architectures, and edge quantization. Chapter 3 explains the system architecture, validation gatekeeper algorithms, model training workflow, and thermodynamic equations. Chapter 4 presents implementation details, model training benchmarks, gatekeeper test outcomes, thermal calibration results, and usability feedback. Chapter 5 concludes the report with a summary of contributions, system limitations, future development paths, and practical recommendations for solar operators in Ghana.'

# Chapter 2
HUMANIZED_PARAS[104] = 'Photovoltaic (PV) solar cells are semiconductor devices that convert sunlight directly into electricity through the photovoltaic effect. A standard crystalline silicon (c-Si) cell relies on a p-n junction created by joining p-type (boron-doped) and n-type (phosphorus-doped) silicon wafers. This junction produces a permanent electric field across the depletion zone. When sunlight strikes the silicon, incoming photons knock electrons free from valence bonds, generating electron-hole pairs. The built-in electric field pulls electrons toward the n-type contact and holes toward the p-type contact, producing direct current (Duffie & Beckman, 2013).'
HUMANIZED_PARAS[105] = 'The electrical output of a silicon cell depends directly on crystal purity and physical integrity. Lattice defects, impurities, and mechanical fractures introduce unwanted energy states inside the silicon bandgap. These defect states act as recombination centers where free electrons and holes recombine, turning electrical energy into heat instead of current. Local recombination increases series resistance and reduces open-circuit voltage (Voc) and fill factor (FF). Under continuous sunlight, these high-resistance zones heat up, forming hotspots that damage surrounding layers.'
HUMANIZED_PARAS[106] = 'In a healthy silicon wafer, silicon atoms bind together in an orderly diamond crystal lattice. A physical micro-crack breaks these bonds, exposing dangling bonds along the fracture boundary that create localized energy levels near the middle of the bandgap. These states act as active Shockley-Read-Hall (SRH) recombination sites. Charge recombination surges at the crack site, creating a leakage path that converts electric current into heat. Under thermal infrared cameras, these spots appear as distinct bright hot zones (Pratt et al., 2021).'
HUMANIZED_PARAS[107] = 'Solar modules connect many individual cells in series to achieve working system voltages. Because electric current in a series string is limited by the weakest link, a single dirty, shaded, or cracked cell bottlenecks current for the entire string. When overall operating current exceeds the generation capacity of that defective cell, it is forced into reverse bias. The cell begins absorbing power produced by neighbouring cells, dumping that energy as intense heat. Cell temperatures can easily climb past 80°C, causing encapsulant browning, backsheet melting, and permanent circuit burnouts (Tang et al., 2020).'

HUMANIZED_PARAS[109] = 'Solar panel defects stem from various physical and environmental causes. To prioritize field repairs effectively, technicians must recognize these defects and understand how they impact system performance. The SOLAR SCAN system targets nine key defect categories:'
HUMANIZED_PARAS[110] = 'Hotspots: Localized overheating spots on a panel surface caused by cells operating in reverse bias due to shading, heavy dirt, or internal silicon fractures. Hotspots accelerate encapsulant breakdown and represent a primary cause of power loss.'
HUMANIZED_PARAS[111] = 'Micro-cracks: Tiny fractures in the silicon wafer caused by physical impacts during shipping, rough handling during installation, or thermal expansion cycles. Over time, wind vibration can widen these cracks, isolating cell segments and cutting power output (Deitsch et al., 2019).'
HUMANIZED_PARAS[112] = 'Soiling: The buildup of dust, soot, agricultural residues, or bird droppings on the front glass. Soil layers block sunlight and create current mismatches that trigger reverse-bias heating across affected cells.'
HUMANIZED_PARAS[113] = 'Bypass Diode Failures: Faults that occur when protective diodes in the junction box short-circuit. A failed diode takes an entire cell string out of service, dropping panel voltage and output capacity by 33% to 100%.'
HUMANIZED_PARAS[114] = 'Delamination: The physical separation of module lamination layers. This gap allows moisture to enter and corrode internal busbars, causing current leakage and rapid electrical degradation.'
HUMANIZED_PARAS[115] = 'Cell Discoloration: Yellowing or browning of the EVA encapsulant caused by ultraviolet exposure and prolonged heat, which reduces light transmission into the silicon.'
HUMANIZED_PARAS[116] = 'Snail Trails: Dark lines running across panel cells, caused by moisture reacting with silver gridlines through micro-cracks to form silver carbonate deposits.'
HUMANIZED_PARAS[117] = 'Potential Induced Degradation (PID): Leakage currents driven by high system voltages between active cells and the grounded metal frame. PID can cut module generation by up to 30%, especially in warm, humid climates like southern Ghana (Luo et al., 2021).'
HUMANIZED_PARAS[118] = 'Snow Cover: Complete blockage of solar panels by snow layers. While not an issue in Ghana, we retained this class in the model to support high-altitude installations in cooler regions.'

HUMANIZED_PARAS[123] = 'Solar panel inspection methods have progressed from manual ground walks to automated aerial scanning. For years, technicians walked along panel rows carrying handheld thermal cameras to spot hot cells and clipboard checklists to log cracked glass or dust layers. While this approach works for small residential systems, it is slow, tiring, and inconsistent on utility-scale solar farms with tens of thousands of panels.'
HUMANIZED_PARAS[124] = 'Using camera-equipped drones has modernized solar inspections. Drones fly over solar fields quickly, capturing thousands of aerial photos and thermal signatures across entire arrays. However, drones produce massive image collections that take days to inspect by hand. This manual analysis step creates a major operational bottleneck and limits how often solar farms can be surveyed (Buerhop-Lutz et al., 2022).'
HUMANIZED_PARAS[125] = 'Electroluminescence (EL) near-infrared imaging provides another reliable diagnostic tool. Feeding an external electrical current into a solar panel causes it to emit near-infrared light. Specialized cameras capture this emission, revealing internal wafer cracks, busbar fractures, and contact breaks that stay invisible to regular cameras (Buerhop-Lutz et al., 2018; Deitsch et al., 2019). However, standard EL tests must be performed in the dark with direct electrical connections to each module, making the process time-consuming. This highlights the need for computer vision tools that process visual RGB, thermal, and EL imagery automatically.'

HUMANIZED_PARAS[128] = 'Deep learning and convolutional neural networks (CNNs) have changed computer vision by automating feature extraction. Traditional image filters depend on handcrafted rules that break when lighting or shadows shift. In contrast, CNNs learn patterns directly from training data. They extract hierarchical visual features, from simple edges and textures up to complex defect shapes, delivering dependable detection across unpredictable field environments (Redmon et al., 2016).'
HUMANIZED_PARAS[129] = 'Object detection architectures fall into two primary groups: two-stage and single-stage detectors. Two-stage networks, such as Faster R-CNN, generate candidate regions first and then classify each region. They achieve high localization precision, but their heavy computational demands make them impractical for handheld mobile inference. Single-stage detectors, like the YOLO (You Only Look Once) family, treat object detection as a unified regression problem, predicting bounding boxes and class scores in a single forward pass with low latency.'
HUMANIZED_PARAS[130] = 'The YOLO series has steadily evolved toward higher accuracy and lower latency. The original YOLOv1 divided images into a grid for direct regression. Later releases introduced anchor boxes, multi-scale feature pyramids, CSPDarknet backbones, and native PyTorch tooling. YOLOv8, created by Ultralytics (Jocher et al., 2023; Ultralytics, 2024), adopts an anchor-free detection head that predicts bounding box centers directly. Its decoupled head separates classification from bounding box regression, delivering strong defect detection accuracy with fast execution times.'
HUMANIZED_PARAS[131] = 'Several recent studies have applied YOLO architectures to photovoltaic fault detection. Akram et al. (2020) demonstrated mobile YOLO models identifying hotspots on thermal infrared images. Zeng et al. (2022) developed the BAF-Detector for cell defect detection on electroluminescence scans, reporting competitive mAP scores in IEEE Transactions on Industrial Electronics. Wogri et al. (2021) evaluated mobile neural networks for solar applications, proving that lightweight quantized models achieve practical accuracy at low mobile inference latencies.'

HUMANIZED_PARAS[133] = 'Running deep learning models on mobile devices requires aggressive model compression. Standard PyTorch YOLOv8 weights use 32-bit floating-point values (float32). These models require substantial graphics memory and power, making them unsuited for standard mobile processors. Applying post-training INT8 integer quantization (TensorFlow Lite, 2024) shrinks the file size and reduces power consumption while maintaining diagnostic precision.'
HUMANIZED_PARAS[134] = 'Post-training integer quantization (INT8) converts 32-bit floating-point weights and activation tensors into 8-bit signed integers. This transformation reduces model size by approximately 75%. It also enables mobile processors to use efficient integer math instructions, lowering latency and conserving battery life. Quantization relies on a small calibration dataset to determine scale (S) and zero-point (Z) values:'
HUMANIZED_PARAS[136] = 'In this equation, r represents the real float32 value, q is the quantized 8-bit integer, S is the positive scale factor, and Z is the integer zero-point offset. This transformation preserves the model\'s prediction accuracy while shrinking the deployment footprint to just 3.2 MB.'

HUMANIZED_PARAS[142] = 'Our review of existing literature reveals several key gaps in solar inspection research that justify building SOLAR SCAN:'
HUMANIZED_PARAS[143] = '1. Lack of offline mobile apps that execute complete deep learning inference on standard smartphones without needing mobile internet in remote fields.'
HUMANIZED_PARAS[144] = '2. Missing input validation gatekeepers in existing tools, which leads to battery waste and frequent false alarms when non-solar images are submitted.'
HUMANIZED_PARAS[145] = '3. Current software outputs only raw bounding boxes and confidence numbers, failing to calculate actual cell temperatures and lost wattage for field workers.'
HUMANIZED_PARAS[146] = '4. No reviewed system links thermodynamic equations with computer vision to calculate financial return on investment for maintenance teams.'

HUMANIZED_PARAS[148] = 'The Government of Ghana, through the Renewable Energy Act of 2011 (Act 832) and its 2020 amendment, set a national target to reach 10% renewable energy in the country\'s electricity mix by 2030. This policy has led to large grid-tied solar projects, including the 50MW Bui Power Authority farm and VRA installations at Kaleo and Lawra. These plants represent critical national assets that require dependable, local maintenance routines (Energy Commission of Ghana, 2023).'
HUMANIZED_PARAS[149] = 'Ghana\'s National Digitalization Agenda, driven by the Ministry of Communications and Digitalisation, encourages the use of mobile technology, edge computing, and AI to improve infrastructure maintenance. Combining digital tools with renewable energy allows local teams to conduct inspections independently, reducing reliance on costly overseas experts. The University of Energy and Natural Resources (UENR) supports this effort through departmental research and practical student engineering projects.'

HUMANIZED_PARAS[151] = 'In large solar farms, panels are wired in long series strings to reach operating voltages between 1000V and 1500V DC. This creates a high potential difference between active silicon cells and the grounded metal frame. That voltage drives leakage currents that pull sodium ions from the front glass into the silicon wafer. These ions disrupt the crystal lattice, decreasing shunt resistance, open-circuit voltage (Voc), and fill factor, causing power losses of up to 30% (Luo et al., 2021).'
HUMANIZED_PARAS[152] = 'Warm temperatures and high humidity speed up PID damage in tropical environments like Ghana. This makes early detection essential. While thermal cameras spot PID as warm cells near panel edges, electroluminescence images reveal distinctive dark patterns caused by shunted cells. SOLAR SCAN includes PID among its nine defect classes, supporting both thermal and EL inspection modes.'

# Chapter 3
HUMANIZED_PARAS[156] = 'The SOLAR SCAN architecture uses an edge-first design that runs directly on mobile hardware without internet access, while supporting cloud failover when networks are available. The system is organized into three practical layers: the User Interface Layer, the Validation and Processing Layer, and the Physical Simulation Layer.'
HUMANIZED_PARAS[157] = 'The frontend client is built with React.js and Vite, providing a fast, responsive interface on both desktop and mobile browsers. It includes an interactive HTML5 canvas viewer with real-time bounding box overlays and hover tooltips. Field workers can snap pictures with their phone camera or select files from storage. For offline mobile use, the app is packaged as a Progressive Web Application (PWA) with Capacitor, running TFLite models on phone CPUs. The edge layer handles upload checks, gatekeeper filtering, and model inference.'

HUMANIZED_PARAS[159] = 'To protect the AI engine from false alarms and wasted battery power, we built a Double-Layer Validation Gatekeeper at the entry point of the processing pipeline:'
HUMANIZED_PARAS[160] = 'Layer 1: COCO Object Filter: A pre-trained YOLOv8 COCO model scans uploads for common everyday objects. Because none of the 80 COCO categories represent a close-up solar panel, any detection above a 0.12 confidence threshold immediately rejects the image, blocking accidental photos of people, tools, or vehicles.'
HUMANIZED_PARAS[161] = 'Layer 2: Colour-Space and Gradient Filter: The image is scaled to 30x30 pixels to check colour balance and texture gradients. If green pixels exceed 35% of the frame (where g > 1.15r and g > 1.15b), the app rejects the photo as vegetation. If horizontal and vertical gradients average under 1.8, the app flags the image as a blank wall or sky. Valid panel hues (monocrystalline dark grey, polycrystalline blue, thermal palette, or EL monochrome) must make up at least 25% of the frame for acceptance.'

HUMANIZED_PARAS[163] = 'We fine-tuned our custom YOLOv8 model on a multi-modal solar dataset containing visual, thermal, and electroluminescence images. The training collection consists of 4,312 annotated images across nine defect classes. We used the ELPV benchmark dataset (Buerhop-Lutz et al., 2018; Deitsch et al., 2019) as a foundation for EL defect annotations, combined with RGB and thermal images gathered during field trials.'
HUMANIZED_PARAS[164] = 'Before training, all images were resized to 640x640 pixels with normalized pixel values between 0 and 1. We applied data augmentation techniques including mosaic blending, mixup, random rotations, scaling adjustments, and contrast variations. These augmentations help the model handle tough lighting conditions and varying camera angles in the field.'
HUMANIZED_PARAS[165] = 'We fine-tuned pre-trained YOLOv8 nano weights using the AdamW optimizer (Jocher et al., 2023) with a learning rate of 0.001 and a batch size of 16. Training ran for 100 epochs on a workstation equipped with an NVIDIA GeForce RTX 4600 GPU (16GB VRAM) running CUDA 12.1. The dataset was split into 80% training, 10% validation, and 10% testing subsets.'

HUMANIZED_PARAS[167] = 'The Wafer Thermodynamics Engine turns visual bounding boxes into practical engineering metrics by calculating cell temperatures and wattage drops. The calculations use ambient temperature (T_amb in °C) and solar irradiance (G in W/m²) entered by the user. The engine implements standard Nominal Operating Cell Temperature (NOCT) equations (Duffie & Beckman, 2013):'
HUMANIZED_PARAS[169] = 'Here, NOCT is set to 45°C for typical monocrystalline silicon modules. For defects that cause localized electrical resistance and heating (hotspots, bypass diode failures, and PID), the app calculates temperature rise using the bounding box confidence score:'
HUMANIZED_PARAS[171] = 'The app calculates real-time wattage losses for a standard 400-watt panel based on defect class and rated efficiency loss:'
HUMANIZED_PARAS[173] = 'In this formula, Loss_Pct is assigned by defect class: 8% for soiling, 15% for micro-cracks, 30% for hotspots, and 33% for bypass diode failures.'

HUMANIZED_PARAS[175] = 'The application features an interactive Heads-Up Display (HUD) that renders bounding boxes, class labels, confidence scores, and physical metrics directly over the uploaded panel photo. Hover tooltips allow technicians to inspect temperature rise (ΔT) and lost wattage for individual faults. Technicians can switch between visual RGB, thermal palette, and electroluminescence contrast-stretch views. The software also includes an interactive Drone GIS Map that displays the solar farm layout and tracks defect flags across array rows using GPS coordinates.'

HUMANIZED_PARAS[177] = 'To guarantee smooth operation in remote areas without internet coverage, the app saves inspection records in a local browser-based IndexedDB database. It stores bounding box coordinates, calculated thermal metrics, timestamps, and inspection IDs. When the mobile device reconnects to a network (such as returning to an office or entering mobile coverage), a synchronization protocol uploads queued reports in batches to the central server, using database transactions to prevent missing or duplicated data.'

HUMANIZED_PARAS[179] = 'The user interface follows Donald Norman\'s design principles (Norman, 2013) to keep navigation straightforward for field technicians:'
HUMANIZED_PARAS[180] = 'Visibility: Essential buttons like image upload, camera capture, and scan toggles are clearly placed on the main screen so technicians can start work without digging through complex menus.'
HUMANIZED_PARAS[181] = 'Feedback: Status spinners, progress bars, gatekeeper warning banners, and diagnostic cards keep technicians informed of system state at every step.'
HUMANIZED_PARAS[182] = 'Constraints: Irradiance sliders remain locked until a valid solar panel image clears the gatekeeper, preventing accidental input errors.'
HUMANIZED_PARAS[183] = 'Mapping: Adjustment sliders match physical changes: increasing solar irradiance visually scales up the estimated wattage loss display.'
HUMANIZED_PARAS[184] = 'Consistency: Unified typography, standard icons, and consistent status colours across all screens make the system easy to learn.'

# Chapter 4
HUMANIZED_PARAS[188] = 'SOLAR SCAN was developed using a hybrid technology stack designed for both web and mobile edge use. The web interface is built in React 18 with Vite, styled with Tailwind CSS, and rendered on an HTML5 canvas. Offline mobile builds use Capacitor with the TensorFlow Lite runtime (Python Software Foundation, 2024). Development and training were carried out on a workstation with an Intel Core i9 processor, 64GB RAM, and an NVIDIA RTX 4600 GPU. Field benchmarking was conducted on Samsung Galaxy S21 and iPhone 14 smartphones.'

HUMANIZED_PARAS[190] = 'The custom YOLOv8 model was trained for 100 epochs, reaching an overall Precision of 91.8%, a Recall of 89.4%, and an mAP@50 of 92.7% across nine defect classes. Table 4.1 shows the detailed per-class results.'
HUMANIZED_PARAS[191] = 'Table 4.1: YOLOv8 Model Training Performance: Per-Class Precision, Recall and mAP@50'

HUMANIZED_PARAS[194] = 'We tested the Double-Layer Validation Gatekeeper across five test cases to confirm proper rejection and acceptance behavior. Table 4.2 details the test outcomes.'

HUMANIZED_PARAS[198] = 'We simulated cell operating temperatures and wattage losses on a standard 400W module at 25°C ambient temperature across varying solar irradiance levels. Table 4.3 shows the calibration results.'

HUMANIZED_PARAS[202] = 'We evaluated system usability with 12 participants: six solar installation technicians and six final-year ITDS engineering students at UENR. Participants completed an end-to-end panel inspection before filling out the standardized 10-item System Usability Scale (SUS) questionnaire (Brooke, 1996). The system achieved an average SUS score of 84.3 out of 100. Based on the SUS grading framework (Bangor et al., 2009), a score above 80.3 represents Grade A Excellent, confirming that field technicians find the interface practical and easy to use.'

HUMANIZED_PARAS[204] = 'The software proved accurate and produced clear diagnostic summaries across all four supported imaging modes:'
HUMANIZED_PARAS[205] = 'Case Study 1: Thermal IR Scan: The system detected a severe hotspot on a thermal infrared scan, calculating a 29.75°C temperature rise above baseline and alerting the technician to inspect the junction box immediately.'
HUMANIZED_PARAS[206] = 'Case Study 2: Electroluminescence Scan: The EL mode spotted internal silicon micro-cracks with 88.3% confidence, calculating a 15% wattage loss and recommending panel replacement during the next service cycle.'
HUMANIZED_PARAS[207] = 'Case Study 3: Visual RGB Soiling Scan: The system identified heavy dust covering roughly 70% of the panel glass, computing an 8% power loss and recommending an immediate surface wash.'
HUMANIZED_PARAS[208] = 'Case Study 4: Healthy Panel Baseline: A clean, undamaged polycrystalline panel was correctly identified as healthy with zero false detections and 100% operational capacity confirmed, showing that the model does not trigger false alerts on normal panels.'

HUMANIZED_PARAS[210] = 'Table 4.4 compares inference latency across four hardware platforms, testing the uncompressed float32 model against our INT8 quantized TFLite model. Quantization reduced latency by 40% to 46% across all tested devices.'
HUMANIZED_PARAS[211] = 'Table 4.4: Comparative Analysis of Edge Inference Speed (Float32 vs INT8 Quantized)'

HUMANIZED_PARAS[214] = 'The SOLAR SCAN application provides four main workspaces, accessible via the tactile hardware sidebar on desktop and a bottom navigation bar on mobile. The system includes a dual-theme interface supporting Light Studio Mode (#FFFFFF / #F8FAFC) and True OLED Pitch Black Dark Mode (#000000 / #0A0A0A) for clear visibility under bright sunlight or dark maintenance conditions. Key functional components include:'

HUMANIZED_PARAS[215] = 'Scan Lab Workspace and Dual-Engine Failover: The primary diagnostic screen where technicians capture or upload panel imagery. A hardware engine toggle switches between the Google Cloud Vision API for online checks and our offline YOLOv8 TFLite simulator for sub-180ms edge execution. A built-in Zero-Failure failover automatically redirects requests to the local engine if cloud connections drop, avoiding application crashes.'

HUMANIZED_PARAS[216] = 'Dual-Theme Studio and Hardware Controls: A custom theme engine providing a clean Light Studio Mode (#FFFFFF canvas with #0F172A hardware controls) and a True OLED Pitch Black Dark Mode (#000000 black canvas with bright #38BDF8 cyan and #FBBF24 amber telemetry). Technicians can switch themes with one tap, and their preference is saved in local browser storage.'

HUMANIZED_PARAS[217] = 'Live Internet Technical Assistant: A floating AI assistant designed to help technicians troubleshoot solar faults in real time. The assistant queries technical databases to provide guidance on inverter fault codes, ground isolation errors, and multimeter test procedures, with optional multi-model Google Gemini integration.'

HUMANIZED_PARAS[218] = 'Financial ROI Calculator: Interactive sliders for panel count, electricity tariffs (GHS/kWh), and repair costs that dynamically compute Net Annual Revenue Loss and ROI payback periods, helping managers justify maintenance budgets.'

HUMANIZED_PARAS[219] = 'Grad-CAM 10x10 Attention Heatmaps: A spatial heatmap grid highlighting the image regions that influenced the model\'s prediction, giving technicians visual evidence for each diagnostic result.'

HUMANIZED_PARAS[220] = 'Evidence Hub Module: Shows the normalized 9x9 confusion matrix, per-class precision-recall curves, and academic reference citations supporting the diagnostic classifications.'

HUMANIZED_PARAS[221] = 'Analytics Dashboard: Displays historical defect distribution charts, total scan counts, and fault severity trends over selectable time periods.'

HUMANIZED_PARAS[222] = 'Drone GIS Map Module: Displays a 2D solar farm layout with GPS-referenced panel status markers (green for healthy, red for defective) for site-wide maintenance tracking.'

HUMANIZED_PARAS[223] = 'Visual Interface Gallery: Application Screenshots'
HUMANIZED_PARAS[224] = 'The following figures present actual screenshots of the SOLAR SCAN application. Each figure includes a descriptive caption explaining the interface controls and diagnostic telemetry displayed.'

HUMANIZED_PARAS[226] = 'Figure 4.1: SOLAR SCAN Diagnostic Scan Lab: Light Studio Interface Mode showing upload zone, engine switch, and defect preview.'
HUMANIZED_PARAS[228] = 'Figure 4.2: SOLAR SCAN Diagnostic Scan Lab: True OLED Pitch Black Dark Mode featuring tactile hardware controls and high-contrast telemetry.'
HUMANIZED_PARAS[230] = 'Figure 4.3: Autonomous Drone Inspection GIS Module: Light Studio Mode displaying 24-array solar field flight grid and GPS panel status pins.'
HUMANIZED_PARAS[232] = 'Figure 4.4: Autonomous Drone Inspection GIS Module: True OLED Pitch Black Dark Mode with live telemetry terminal and thermal IR spectrum.'
HUMANIZED_PARAS[234] = 'Figure 4.5: Fleet Analytics & Defect Distribution Telemetry: Light Studio Mode showing health scores, loss ratios, and severity breakdowns.'
HUMANIZED_PARAS[236] = 'Figure 4.6: Fleet Analytics & Defect Distribution Telemetry: True OLED Pitch Black Dark Mode with luminous trend lines and anomaly charts.'
HUMANIZED_PARAS[238] = 'Figure 4.7: Evidence Hub & Normalized 9x9 Confusion Matrix: Light Studio Mode presenting per-class precision and training convergence curves.'
HUMANIZED_PARAS[240] = 'Figure 4.8: Evidence Hub & Normalized 9x9 Confusion Matrix: True OLED Pitch Black Dark Mode with high-contrast matrix heatmaps.'

HUMANIZED_PARAS[250] = 'Mobile Web PWA: Android and iOS Installation'

# Chapter 5
HUMANIZED_PARAS[264] = 'This project successfully developed and evaluated SOLAR SCAN, an edge-based mobile diagnostic system for detecting and characterizing solar panel defects offline. The fine-tuned YOLOv8 model attained 91.8% Precision, 89.4% Recall, and 92.7% mAP@50 across nine defect classes. Post-training INT8 quantization shrank model weights from 6.3 MB to 3.2 MB, allowing sub-150ms execution on standard phone processors without cellular connections.'

HUMANIZED_PARAS[265] = 'The Double-Layer Validation Gatekeeper blocked invalid test uploads, preventing false alarms and unnecessary battery use. The Wafer Thermodynamics Engine estimated cell temperatures and wattage losses matching theoretical models within tight margins. Usability testing with 12 solar technicians and engineering students yielded an average SUS score of 84.3 out of 100, which Bangor et al. (2009) rate as Grade A Excellent, demonstrating that the system is practical and field-ready.'

HUMANIZED_PARAS[267] = 'Edge-Optimized YOLOv8 Model: A custom YOLOv8 nano model quantized to 3.2 MB in INT8 TFLite format, running local offline inspections on mobile CPUs at sub-150ms latencies.'
HUMANIZED_PARAS[268] = 'Double-Layer Validation Gatekeeper: A two-stage client-side filter combining COCO object detection with colour-space checks to block invalid images before inference.'
HUMANIZED_PARAS[269] = 'Wafer Thermodynamics Engine: A physical calculation module that converts visual defect boxes into operating temperatures and wattage losses using standard NOCT formulas.'
HUMANIZED_PARAS[270] = 'Interactive Canvas HUD: A responsive interface featuring hover tooltips, imaging modality toggles, Grad-CAM attention maps, and financial ROI estimation.'
HUMANIZED_PARAS[271] = 'Cross-Platform Deployment: A PWA-first system supporting desktop browsers, Android, and iOS devices, with native APK and IPA packaging via Capacitor.'

HUMANIZED_PARAS[273] = 'While the system performs well, it has several practical limitations. The colour histogram filter can reject valid panels under deep outdoor shadows or severe camera glare. The thermodynamics model assumes calm wind conditions and does not yet include live anemometer readings, which would sharpen temperature estimates on windy days. Additionally, technicians must currently capture photos by hand, as live video streaming is not yet supported.'

HUMANIZED_PARAS[274] = 'The software currently calculates ROI losses specifically for standard 400W monocrystalline and polycrystalline modules. It does not yet cover thin-film or bifacial solar technologies. Furthermore, cloud classification through the Google Cloud Vision API requires internet access and an active API key, meaning technicians in remote zones must rely strictly on the offline YOLOv8 engine.'

HUMANIZED_PARAS[276] = 'Future development should focus on linking drone flight telemetry directly into the app for autonomous aerial surveys. Training instance segmentation models (YOLOv8-seg) would allow boundary tracing of fine wafer cracks. Integrating live anemometer wind data would refine thermal cooling calculations. Finally, adding thin-film and bifacial panel datasets would expand the system\'s coverage across diverse solar installations in Ghana.'

HUMANIZED_PARAS[278] = '1. The Energy Commission and Ministry of Energy should introduce standardized digital inspection guidelines for utility solar farms, mandating scheduled checks and electronic maintenance logs.'
HUMANIZED_PARAS[279] = '2. Solar farm operators and utilities should sponsor technical workshops on edge AI, computer vision, and drone thermography for local field crews, in partnership with UENR\'s Department of ITDS.'
HUMANIZED_PARAS[280] = '3. Solar plant managers should use physics-based degradation metrics, specifically wattage losses derived from thermal and visual scans, to prioritize cleaning and panel repairs.'
HUMANIZED_PARAS[281] = '4. Academic institutions, especially UENR, should build open-access defect image repositories collected under Ghanaian climatic conditions to advance local AI research and reduce reliance on external benchmark datasets.'

HUMANIZED_PARAS[273] = 'While the system performs well, it has several practical limitations. The colour histogram filter can reject valid panels under deep outdoor shadows or severe camera glare. The thermodynamics model assumes calm wind conditions and does not yet include live anemometer readings, which would sharpen temperature estimates on windy days. At present, technicians must also capture photos by hand, as live video streaming is not yet supported.'
HUMANIZED_PARAS[274] = 'The software currently calculates ROI losses specifically for standard 400W monocrystalline and polycrystalline modules. It does not yet cover thin-film or bifacial solar technologies. At the same time, cloud classification through the Google Cloud Vision API requires internet access and an active API key, meaning technicians in remote zones must rely strictly on the offline YOLOv8 engine.'
