import React, { useState, useRef, useEffect } from "react";

// Standard Chat Icon (SVG)
const ChatIcon = ({ size = 22, color = "currentColor" }) => (
  <svg
    viewBox="0 0 24 24"
    width={size}
    height={size}
    fill="none"
    stroke={color}
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    style={{ display: "inline-block", verticalAlign: "middle" }}
  >
    <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" />
  </svg>
);

// Close Icon (SVG)
const CloseIcon = ({ size = 18, color = "currentColor" }) => (
  <svg
    viewBox="0 0 24 24"
    width={size}
    height={size}
    fill="none"
    stroke={color}
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <line x1="18" y1="6" x2="6" y2="18" />
    <line x1="6" y1="6" x2="18" y2="18" />
  </svg>
);

// Trash Can Icon for Clear Chat (SVG)
const TrashIcon = ({ size = 16, color = "currentColor" }) => (
  <svg
    viewBox="0 0 24 24"
    width={size}
    height={size}
    fill="none"
    stroke={color}
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <polyline points="3 6 5 6 21 6" />
    <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2" />
    <line x1="10" y1="11" x2="10" y2="17" />
    <line x1="14" y1="11" x2="14" y2="17" />
  </svg>
);

// Send Icon (SVG)
const SendIcon = ({ size = 16, color = "currentColor" }) => (
  <svg
    viewBox="0 0 24 24"
    width={size}
    height={size}
    fill="none"
    stroke={color}
    strokeWidth="2.2"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <line x1="22" y1="2" x2="11" y2="13" />
    <polygon points="22 2 15 22 11 13 2 9 22 2" />
  </svg>
);

// Expanded local offline database covering solar panels, energy, batteries, and everything solar
const SOLAR_KNOWLEDGE = [
  {
    keys: ["hi", "hello", "hey", "greet", "who are you"],
    response: "Hello! I am your SolarScan AI Technical Assistant. I can help you answer any questions about solar panels, photovoltaic technology, battery storage, inverters, system sizing, ROI calculations, and defect detection. What would you like to know?"
  },
  {
    keys: ["hotspot", "hot spot", "overheat", "burning", "burn"],
    response: "Thermal hotspots occur when solar cells are shaded, cracked, or electrically mismatched, acting as resistive loads that dissipate power as high heat. Urgency: CRITICAL. Recommendation: Shutdown and IR-inspect the string. If the temperature delta (ΔT) exceeds 25°C relative to surrounding areas, inspect the bypass diodes in the junction box or schedule panel replacement."
  },
  {
    keys: ["crack", "microcrack", "broken", "shatter", "glass"],
    response: "Solar cell micro-cracks are internal fractures in silicon wafers caused by mechanical strain, wind/hail loading, or improper handling. While invisible to the naked eye, they show up clearly under EL (Electroluminescence) scans. Recommendation: Monitor quarterly. If micro-cracks isolate wafer sections causing cell power output to drop by more than 10%, plan module replacement."
  },
  {
    keys: ["soiling", "dust", "sand", "dirt", "dirty", "clean", "wash"],
    response: "Soiling involves the accumulation of atmospheric dust, sand, or bird droppings on the panel glass, blocking incoming solar irradiance. It is the leading cause of reversible yield loss. Recommendation: Implement a monthly maintenance wash using deionised water and soft squeegees. Avoid abrasive scrubbers to prevent stripping the anti-reflective glass coating."
  },
  {
    keys: ["delamination", "peeling", "water", "moisture"],
    response: "Delamination is the peeling apart of the panel encapsulation layers (tempered glass, EVA, solar cells, and backsheet) due to moisture entry. This leads to circuit corrosion and leakage currents. Recommendation: Apply silicone UV sealants if localized peeling covers less than 5% of the surface area. Replace the panel if delamination exceeds 20%."
  },
  {
    keys: ["pid", "voltage", "potential", "degradation"],
    response: "Potential Induced Degradation (PID) is caused by leakage currents between active cells and the grounded metal frame, draining system power. Recommendation: Verify system grounding. Use an overnight reverse-PID voltage injection treatment (charging the string positive to ground) to reverse the polarization damage."
  },
  {
    keys: ["inverter", "string inverter", "microinverter", "micro-inverter", "hybrid inverter"],
    response: "Solar inverters convert DC power generated by solar panels into AC power used by home appliances or fed into the utility grid. Common types are String Inverters (centralized, cost-effective), Microinverters (installed per-panel, optimizes shaded fleets), and Hybrid Inverters (combines solar conversion and battery storage interfaces)."
  },
  {
    keys: ["battery", "batteries", "storage", "lithium", "lfp", "lead-acid", "backup", "kwh"],
    response: "Solar battery storage stores excess energy generated during the day for use at night or during blackouts. Modern systems primarily use Lithium Iron Phosphate (LFP / LiFePO4) chemistry due to its long cycle life (3000-6000 cycles), high depth of discharge (90%+), and safety compared to older lead-acid batteries."
  },
  {
    keys: ["net metering", "net-metering", "grid-tied", "sell back"],
    response: "Net Metering is a billing mechanism that credits solar system owners for the electricity they add to the utility grid. When panels produce more energy than is consumed, the excess flows to the grid, spinning the meter backward and providing credits to offset utility bills."
  },
  {
    keys: ["tilt", "angle", "orientation", "azimuth", "direction"],
    response: "To maximize annual solar energy yield, solar panels should be tilted at an angle roughly equal to the geographical latitude of the installation site. In the Northern Hemisphere, panels should face true South (180° Azimuth); in the Southern Hemisphere, they should face true North (0° Azimuth) to receive peak solar irradiance throughout the day."
  },
  {
    keys: ["monocrystalline", "polycrystalline", "thin film", "mono vs poly", "solar cell types"],
    response: "Monocrystalline panels are made from a single pure silicon crystal, offering the highest efficiency (19% to 22%+) and a sleek black aesthetic. Polycrystalline panels are made from melted fragments of silicon, have slightly lower efficiency (15% to 18%), and a blue speckled appearance. Thin-film panels are flexible but have low efficiency (10% to 13%), used for specialized structures."
  },
  {
    keys: ["efficiency", "loss", "temperature coefficient"],
    response: "Solar panel cell efficiency determines how much sunlight is converted into usable electricity. Standard residential panels operate at 18-22% efficiency. As temperature increases above 25°C, efficiency drops slightly due to the silicon's 'temperature coefficient' (typically losing 0.3% to 0.4% power per 1°C increase)."
  },
  {
    keys: ["cost", "price", "savings", "tax credit", "payback", "watts"],
    response: "A residential solar system typically costs between $2.80 and $3.50 per watt before incentives. In many regions, tax credits (like the US Federal ITC of 30%) reduce this cost significantly. The average payback period (when the electricity savings cover the system cost) is between 6 to 10 years, followed by 15-20 years of free energy."
  },
  {
    keys: ["yolo", "tflite", "model", "neural", "grad-cam"],
    response: "This application integrates an optimized YOLOv8n (You Only Look Once v8 nano) network compiled to TensorFlow Lite INT8. The model runs locally in the client browser, detecting anomaly bounding boxes (defect class coordinates) and displaying Grad-CAM activation heatmaps in ~180 milliseconds, ensuring fully private, offline scanning."
  },
  {
    keys: ["roi", "calculator", "finance", "revenue"],
    response: "Our ROI calculator computes potential yield losses by taking your fleet inputs (Panels × Panel Yield × Peak Sun Hours × Tariff rate) and multiplying by the AI-detected Efficiency Loss percentage. It then calculates corrective repair costs ($110 per unit + $250 service fee) to estimate your net annual retained savings."
  },
  {
    keys: ["project", "uenr", "fyp"],
    response: "SolarScan AI is built as a Final Year Project (FYP) for the University of Energy and Natural Resources (UENR). It aims to offer engineers and field technicians a modern, portable, AI-powered diagnostic framework to optimize solar farm efficiencies."
  },
  {
    keys: ["size", "sizing", "how many panels", "kw rating", "calculate panels", "system size"],
    response: "To calculate your required solar system size, divide your monthly energy consumption (in kWh) by your area's average peak sun hours per month, then multiply by a system efficiency buffer (typically 1.15 to 1.20 to account for inverter and wiring losses).\n\nFor example, if a home uses 900 kWh per month in an area receiving 4.5 peak sun hours per day:\n• Daily consumption: 900 kWh / 30 days = 30 kWh/day\n• Required system power: 30 kWh / 4.5 hours = 6.67 kW DC\n• With a 1.20 loss factor: 6.67 kW × 1.20 = 8.0 kW system size.\n• Panel count: An 8.0 kW system using standard 400W monocrystalline modules requires exactly 20 panels (8,000W / 400W)."
  },
  {
    keys: ["science", "how do panels work", "physics", "silicon", "photon", "semiconductor", "photovoltaic"],
    response: "Solar panels generate electricity using the Photovoltaic (PV) Effect. When photons from sunlight strike a solar cell made of semiconductor materials (like silicon), they transfer energy to bound electrons, knocking them free and creating electron-hole pairs.\n\nKey physical steps:\n1. **P-N Junction**: Silicon wafers are doped to create a negative layer (n-type) and a positive layer (p-type), establishing an internal electric field.\n2. **Electron Flow**: Free electrons are forced by the electric field to flow toward the n-type side, while holes move to the p-type side.\n3. **Current Collection**: Metal contact grids on top of the cell collect these moving electrons, directing them into external circuits as Direct Current (DC) electricity."
  },
  {
    keys: ["bifacial", "double-sided", "double sided", "albedo"],
    response: "Bifacial solar panels feature light-absorbing cells on both the front and rear faces of the module. While the front face captures direct sunlight, the rear face captures indirect light reflected off the surrounding ground (known as 'albedo' light).\n\nAdvantages:\n• **Higher Yield**: Can generate 5% to 30% more energy than standard monofacial panels depending on ground reflectivity.\n• **Optimal Pairings**: Perfect for highly reflective surfaces like white gravel, concrete, sand, or snow. They are widely used in ground-mounted utility-scale systems and carports."
  },
  {
    keys: ["off-grid", "offgrid", "grid-tied", "hybrid system", "stand alone"],
    response: "Solar configurations fall into three main types:\n\n1. **Grid-Tied System**: Connected directly to the utility grid. Simple and economical because excess energy is sent to the grid via net metering, removing the absolute need for batteries.\n2. **Off-Grid System**: Completely isolated. Requires a massive battery storage bank to store energy for nighttime and multi-day storms, plus a backup generator to ensure continuous power.\n3. **Hybrid System**: Combines both worlds. It is grid-tied but includes a home battery. It prioritizes battery self-consumption during peak utility rate hours and provides backup power during grid blackouts."
  },
  {
    keys: ["shading", "shadow", "tree", "bypass diode", "obstruction"],
    response: "Shading even a tiny portion of a solar panel can severely degrade the output of the entire panel string, as shaded cells act as high-resistance blockages. To prevent this, manufacturers integrate **Bypass Diodes** inside the panel's junction box.\n\nHow it works:\n• **Bypass Path**: When a cell is shaded, the bypass diode activates to route the electrical current around the shaded segment, sacrificing that section to keep the rest of the string running at full capacity.\n• **Design Optimization**: For heavily shaded roofs, **Microinverters** or **Power Optimizers** are recommended, as they perform Maximum Power Point Tracking (MPPT) at the individual panel level, preventing one shaded panel from dragging down the rest."
  },
  {
    keys: ["lifetime", "lifespan", "life span", "warranty", "degradation rate", "durability"],
    response: "Standard residential solar panels are extremely durable and feature a lifespan of **25 to 30 years**. Most Tier 1 manufacturers provide a double-layered warranty:\n\n• **Product Warranty**: Covers material defects, glass breakage, and manufacturing faults, typically lasting 12 to 25 years.\n• **Performance Warranty**: Guarantees that the panel output will not degrade too quickly. A standard warranty guarantees at least 90% power output at year 10, and 80% to 85% at year 25.\n• **Degradation Rate**: Silicon panels degrade at an average rate of **0.5% per year**. After 25 years, a high-quality panel will still operate at roughly 87.5% of its initial rated capacity."
  },
  {
    keys: ["carbon", "co2", "environment", "climate", "green energy", "benefit", "offset"],
    response: "Solar energy is one of the cleanest and most sustainable power sources available, generating zero carbon dioxide, greenhouse gases, or particulate air pollution during operation.\n\nEnvironmental Impacts:\n• **Carbon Offset**: An average residential 8 kW solar system offsets approximately 150 tons of CO2 over its 25-year lifetime, equivalent to planting 3,500 trees or driving 300,000 fewer miles in a gasoline car.\n• **Energy Payback Time (EPBT)**: The time a panel takes to generate the energy required to manufacture, package, and transport it. Modern silicon solar panels reach their energy payback within **1 to 2 years** of active operation, yielding 23+ years of completely net-positive clean energy."
  },
  {
    keys: ["maintenance", "clean", "safety", "danger", "fire", "shock"],
    response: "Solar panels require minimal maintenance because they have no moving parts. However, regular upkeep and safety protocols are important:\n\n• **Inspection**: Schedule a visual scan twice a year to check for accumulated leaves, bird nesting under panels, or surface cracking.\n• **Safety & Shock Risks**: Solar strings operate at high DC voltages (up to 600V for residential, 1500V for commercial). Never touch exposed cables or try to repair junction boxes yourself. Use the app's rapid shutdown protocols or call a certified installer.\n• **Fire Safety**: Electrical arcing due to damaged connectors is the main cause of solar fires. Keep your inverter clear of clutter and monitor standard safety alerts."
  },
  {
    keys: ["powerwall", "tesla", "home storage", "battery capacity"],
    response: "Home batteries like the Tesla Powerwall store excess solar power generated during the day for use at night or during blackouts. A typical unit (e.g. Powerwall 3) features a capacity of **13.5 kWh** and an output of **11.5 kW** continuous power, equipped with a built-in hybrid solar inverter. Combining solar with smart battery storage protects homeowners from grid outages and maximizes savings in utility regions with time-of-use pricing models."
  }
];

// Helper semantic matcher for offline topics
function matchSolarTopic(queryText) {
  const query = queryText.toLowerCase();
  let bestMatch = null;
  let maxMatchedKeysCount = 0;
  
  for (const item of SOLAR_KNOWLEDGE) {
    let matchCount = 0;
    for (const key of item.keys) {
      if (query.includes(key)) {
        matchCount++;
      }
    }
    if (matchCount > maxMatchedKeysCount) {
      maxMatchedKeysCount = matchCount;
      bestMatch = item.response;
    }
  }
  
  if (bestMatch) {
    return bestMatch;
  }
  
  // Semantic word overlap fallback
  const solarContextWords = [
    "solar", "panel", "energy", "sun", "electricity", "photovoltaic", "pv", "battery", 
    "inverter", "grid", "clean", "defect", "power", "watt", "volt", "charge", "renew", 
    "green", "carbon", "cell", "current", "dc", "ac"
  ];
  const hasSolarContext = solarContextWords.some(w => query.includes(w));
  if (hasSolarContext) {
    return "Photovoltaic (PV) systems generate Direct Current (DC) electricity using semiconductor layers, which is converted to Alternating Current (AC) by an inverter. If your query is related to solar design, sizing, sizing equations, battery backup capacity, ROI calculations, or panel defects (like hotspots, microcracks, or soiling), ask me for specific technical details! (Or enter a working Google API key in the Scan Lab tab to enable live Gemini AI questions).";
  }
  
  return "I am your SolarScan AI Technical Assistant, trained specifically to answer questions about clean energy, solar PV arrays, batteries, inverters, ROI calculations, and cell defect diagnostics. If you have questions about solar technology or defect scanning, I'd be happy to assist you!";
}

// Google Gemini API query function
async function queryGemini(prompt, apiKey) {
  const response = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`,
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        contents: [
          {
            role: "user",
            parts: [
              {
                text: `You are SolarScan AI Assistant, an expert clean energy and solar PV systems engineer. Answer the user's questions about solar panels, solar energy, solar cell defects, batteries, inverters, installation, grid systems, and clean energy topics. Respond directly, using formatting (bullet points, clear paragraphs) when appropriate. Keep it technical, engaging, and relatively concise (maximum 3 paragraphs). If the question is completely unrelated to solar energy or clean technology, gently guide the user back to solar topics. Question: "${prompt}"`
              }
            ]
          }
        ]
      })
    }
  );
  
  if (!response.ok) {
    throw new Error(`Gemini API call failed with status ${response.status}`);
  }
  
  const data = await response.json();
  const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!text) throw new Error("Empty response candidate");
  return text;
}

export default function Chatbot({ apiKey }) {
  const [isOpen, setIsOpen] = useState(false);
  const [messages, setMessages] = useState([
    {
      id: "m0",
      text: "Hello! I am your SolarScan AI Technical Assistant. Ask me any questions about solar panels, batteries, inverters, clean energy, or defect diagnostics. (Link your Google API key to enable live generative AI responses!)",
      sender: "bot",
      time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    }
  ]);
  const [inputText, setInputText] = useState("");
  const [isTyping, setIsTyping] = useState(false);

  const messagesEndRef = useRef(null);

  // Repositioning Drag hooks
  const [position, setPosition] = useState({ x: 0, y: 0 });
  const isDraggingRef = useRef(false);
  const dragStartRef = useRef({ mouseX: 0, mouseY: 0, offsetX: 0, offsetY: 0 });
  const hasMovedRef = useRef(false);
  const [isMobile, setIsMobile] = useState(typeof window !== "undefined" ? window.innerWidth <= 768 : false);

  useEffect(() => {
    const handleResize = () => {
      setIsMobile(window.innerWidth <= 768);
    };
    window.addEventListener("resize", handleResize);
    return () => window.removeEventListener("resize", handleResize);
  }, []);

  useEffect(() => {
    const handlePointerMove = (e) => {
      if (!isDraggingRef.current) return;
      
      const clientX = e.touches ? e.touches[0].clientX : e.clientX;
      const clientY = e.touches ? e.touches[0].clientY : e.clientY;
      
      const diffX = clientX - dragStartRef.current.mouseX;
      const diffY = clientY - dragStartRef.current.mouseY;
      
      if (Math.abs(diffX) > 5 || Math.abs(diffY) > 5) {
        hasMovedRef.current = true;
      }
      
      const newOffsetX = dragStartRef.current.offsetX - diffX;
      const newOffsetY = dragStartRef.current.offsetY - diffY;
      
      // Boundaries
      const buttonSize = 56;
      const margin = 24;
      const maxOffsetX = window.innerWidth - buttonSize - margin;
      const minOffsetX = -margin;
      const maxOffsetY = window.innerHeight - buttonSize - margin;
      const minOffsetY = -margin;
      
      const constrainedX = Math.max(minOffsetX, Math.min(maxOffsetX, newOffsetX));
      const constrainedY = Math.max(minOffsetY, Math.min(maxOffsetY, newOffsetY));
      
      setPosition({ x: constrainedX, y: constrainedY });
    };
    
    const handlePointerUp = () => {
      if (isDraggingRef.current) {
        isDraggingRef.current = false;
      }
    };
    
    window.addEventListener("mousemove", handlePointerMove);
    window.addEventListener("mouseup", handlePointerUp);
    window.addEventListener("touchmove", handlePointerMove, { passive: false });
    window.addEventListener("touchend", handlePointerUp);
    
    return () => {
      window.removeEventListener("mousemove", handlePointerMove);
      window.removeEventListener("mouseup", handlePointerUp);
      window.removeEventListener("touchmove", handlePointerMove);
      window.removeEventListener("touchend", handlePointerUp);
    };
  }, []);

  const handlePointerDown = (e) => {
    const clientX = e.touches ? e.touches[0].clientX : e.clientX;
    const clientY = e.touches ? e.touches[0].clientY : e.clientY;
    
    isDraggingRef.current = true;
    hasMovedRef.current = false;
    dragStartRef.current = {
      mouseX: clientX,
      mouseY: clientY,
      offsetX: position.x,
      offsetY: position.y
    };
  };

  const handleTriggerClick = (e) => {
    e.preventDefault();
    if (!hasMovedRef.current) {
      setIsOpen(true);
    }
  };

  // Auto scroll to bottom
  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  useEffect(() => {
    if (isOpen) {
      scrollToBottom();
    }
  }, [messages, isTyping, isOpen]);

  // Suggested prompts
  const SUGGESTED_PROMPTS = [
    "What are monocrystalline cells?",
    "How does a solar inverter work?",
    "Explain solar batteries & LFP",
    "What is net metering?"
  ];

  // Helper to clear chat history
  const handleClearHistory = () => {
    setMessages([
      {
        id: `m-${Date.now()}`,
        text: `Chat history cleared. Hello! How can I assist you with solar panels or clean energy diagnostics today?`,
        sender: "bot",
        time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
      }
    ]);
  };

  const handleSend = async (textToSend) => {
    const text = textToSend.trim();
    if (!text) return;

    // Add user message
    const userMsg = {
      id: `u-${Date.now()}`,
      text,
      sender: "user",
      time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    };
    setMessages(prev => [...prev, userMsg]);
    setInputText("");
    setIsTyping(true);

    try {
      let botResponseText = "";
      let apiWarningPrefix = "";

      // 1. Try to use Google Gemini API if key is linked
      const isDemoKey = apiKey === "demo" || apiKey === "simulate";
      if (apiKey && !isDemoKey) {
        try {
          botResponseText = await queryGemini(text, apiKey);
        } catch (apiErr) {
          console.warn("Live Gemini API query failed, falling back to local database:", apiErr);
          const errMsg = apiErr.message || apiErr.toString();
          if (errMsg.includes("403") || errMsg.includes("status 403")) {
            apiWarningPrefix = "⚠️ [Google API Key Authorization Issue (403)] Your linked key is restricted or lacks the 'Generative Language API' enabled in Google Cloud. Running in high-fidelity offline backup mode:\n\n";
          } else {
            apiWarningPrefix = `⚠️ [Gemini API Error: ${errMsg}] Running in high-fidelity offline backup mode:\n\n`;
          }
        }
      }

      // 2. Fallback to local keyword database if no key or API failed
      if (!botResponseText) {
        botResponseText = apiWarningPrefix + matchSolarTopic(text);
      }

      const botMsg = {
        id: `b-${Date.now()}`,
        text: botResponseText,
        sender: "bot",
        time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
      };
      setMessages(prev => [...prev, botMsg]);
    } catch (err) {
      console.error("Chatbot processing error:", err);
      setMessages(prev => [
        ...prev,
        {
          id: `b-err-${Date.now()}`,
          text: "An error occurred while generating a response. Please check your network connection and API key configurations.",
          sender: "bot",
          time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
        }
      ]);
    } finally {
      setIsTyping(false);
    }
  };

  return (
    <div
      style={{
        position: "fixed",
        bottom: isOpen 
          ? (isMobile ? "calc(64px + env(safe-area-inset-bottom, 0px) + 12px)" : "24px") 
          : `${24 + position.y}px`,
        right: isOpen 
          ? (isMobile ? "16px" : "24px") 
          : `${24 + position.x}px`,
        left: (isOpen && isMobile) ? "16px" : "auto",
        zIndex: 9999,
        fontFamily: "var(--font-sans)",
        userSelect: isDraggingRef.current ? "none" : "auto"
      }}
    >
      {/* 1. Floating Trigger Button */}
      {!isOpen && (
        <button
          onMouseDown={handlePointerDown}
          onTouchStart={handlePointerDown}
          onClick={handleTriggerClick}
          style={{
            width: "56px",
            height: "56px",
            borderRadius: "50%",
            background: "linear-gradient(135deg, var(--cyan), var(--blue))",
            color: "#000000",
            border: "none",
            cursor: isDraggingRef.current ? "grabbing" : "grab",
            boxShadow: "0 4px 20px rgba(0, 229, 255, 0.4), inset 0 0 10px rgba(255, 255, 255, 0.3)",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            transition: isDraggingRef.current ? "none" : "all 0.3s cubic-bezier(0.16, 1, 0.3, 1)",
            animation: isDraggingRef.current ? "none" : "pulse 2s infinite",
            touchAction: "none"
          }}
          title="Drag to move / Click to chat"
        >
          <ChatIcon size={24} color="#000000" />
        </button>
      )}

      {/* 2. Chat Drawer Window */}
      {isOpen && (
        <div
          style={{
            width: isMobile ? "auto" : "380px",
            height: isMobile ? "calc(100dvh - 160px)" : "520px",
            maxHeight: "520px",
            background: "var(--card)",
            backdropFilter: "blur(16px)",
            border: "1px solid var(--border)",
            boxShadow: "0 10px 40px rgba(0,0,0,0.5), 0 0 20px rgba(0, 229, 255, 0.1)",
            borderRadius: "16px",
            display: "flex",
            flexDirection: "column",
            overflow: "hidden",
            animation: "slideIn 0.3s cubic-bezier(0.16, 1, 0.3, 1)"
          }}
        >
          {/* Header Banner */}
          <header
            style={{
              padding: "14px 16px",
              background: "linear-gradient(135deg, var(--surface), var(--card))",
              borderBottom: "1px solid var(--border)",
              display: "flex",
              alignItems: "center",
              justifyContent: "space-between",
            }}
          >
            <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
              <div
                style={{
                  width: "10px",
                  height: "10px",
                  borderRadius: "50%",
                  background: apiKey ? "var(--green)" : "var(--amber)",
                  boxShadow: `0 0 8px ${apiKey ? "var(--green)" : "var(--amber)"}`,
                }}
              />
              <div>
                <h3 style={{ fontSize: "14px", fontWeight: 700, color: "var(--cyan)", margin: 0, lineHeight: 1.2 }}>
                  SolarScan Assistant
                </h3>
                <span style={{ fontSize: "9px", color: "var(--text-mid)" }}>
                  {apiKey ? "Live Generative AI Chat Active" : "Local Smart Solar Simulator"}
                </span>
              </div>
            </div>
            
            <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
              {/* Clear History Button */}
              <button
                onClick={handleClearHistory}
                style={{
                  background: "transparent",
                  border: "none",
                  color: "var(--text-dim)",
                  cursor: "pointer",
                  padding: "4px",
                  display: "flex",
                  alignItems: "center",
                  transition: "color 0.2s"
                }}
                title="Clear Chat History"
              >
                <TrashIcon size={16} color="var(--text-mid)" />
              </button>
              
              {/* Close Button */}
              <button
                onClick={() => setIsOpen(false)}
                style={{
                  background: "transparent",
                  border: "none",
                  color: "var(--text-mid)",
                  cursor: "pointer",
                  padding: "4px",
                  display: "flex",
                  alignItems: "center",
                  transition: "color 0.2s"
                }}
                title="Close panel"
              >
                <CloseIcon size={16} color="var(--text-mid)" />
              </button>
            </div>
          </header>

          {/* Messages Area */}
          <div
            style={{
              flex: 1,
              padding: "16px",
              overflowY: "auto",
              display: "flex",
              flexDirection: "column",
              gap: "12px",
              background: "rgba(0,0,0,0.1)"
            }}
          >
            {messages.map((m) => (
              <div
                key={m.id}
                style={{
                  alignSelf: m.sender === "user" ? "flex-end" : "flex-start",
                  maxWidth: "85%",
                  display: "flex",
                  flexDirection: "column",
                  gap: "2px"
                }}
              >
                <div
                  style={{
                    background: m.sender === "user" ? "linear-gradient(135deg, var(--cyan), var(--blue))" : "var(--surface)",
                    color: m.sender === "user" ? "#000" : "var(--text)",
                    border: m.sender === "user" ? "none" : "1px solid var(--border)",
                    padding: "10px 14px",
                    borderRadius: m.sender === "user" ? "12px 12px 2px 12px" : "12px 12px 12px 2px",
                    fontSize: "12px",
                    lineHeight: 1.5,
                    whiteSpace: "pre-wrap",
                    boxShadow: m.sender === "user" ? "0 2px 8px rgba(0, 229, 255, 0.15)" : "none"
                  }}
                >
                  {m.text}
                </div>
                <span style={{ fontSize: "8px", color: "var(--text-dim)", alignSelf: m.sender === "user" ? "flex-end" : "flex-start", fontFamily: "var(--font-mono)", marginTop: "2px" }}>
                  {m.time}
                </span>
              </div>
            ))}

            {/* Typing Indicator */}
            {isTyping && (
              <div style={{ alignSelf: "flex-start", display: "flex", flexDirection: "column", gap: "2px" }}>
                <div
                  style={{
                    background: "var(--surface)",
                    border: "1px solid var(--border)",
                    padding: "10px 18px",
                    borderRadius: "12px 12px 12px 2px",
                    display: "flex",
                    gap: "4px",
                    alignItems: "center",
                    height: "32px"
                  }}
                >
                  <span className="dot-pulse" style={{ width: "5px", height: "5px", background: "var(--cyan)", borderRadius: "50%" }} />
                  <span className="dot-pulse" style={{ width: "5px", height: "5px", background: "var(--cyan)", borderRadius: "50%", animationDelay: "0.2s" }} />
                  <span className="dot-pulse" style={{ width: "5px", height: "5px", background: "var(--cyan)", borderRadius: "50%", animationDelay: "0.4s" }} />
                </div>
              </div>
            )}
            <div ref={messagesEndRef} />
          </div>

          {/* Quick-Prompt Suggestions Footer */}
          {messages.length === 1 && (
            <div style={{ padding: "8px 12px", display: "flex", flexDirection: "column", gap: "6px", borderTop: "1px solid var(--border)", background: "rgba(0,0,0,0.05)" }}>
              <span style={{ fontSize: "9px", color: "var(--text-mid)", fontFamily: "var(--font-mono)", textTransform: "uppercase" }}>
                Suggested Prompts:
              </span>
              <div style={{ display: "flex", gap: "6px", flexWrap: "wrap" }}>
                {SUGGESTED_PROMPTS.map((p) => (
                  <button
                    key={p}
                    onClick={() => handleSend(p)}
                    style={{
                      background: "var(--surface)",
                      border: "1px solid var(--border)",
                      color: "var(--cyan)",
                      borderRadius: "6px",
                      padding: "4px 8px",
                      fontSize: "10px",
                      cursor: "pointer",
                      textAlign: "left",
                      transition: "all 0.2s",
                      fontFamily: "var(--font-mono)",
                    }}
                  >
                    {p}
                  </button>
                ))}
              </div>
            </div>
          )}

          {/* Chat Input Bar */}
          <form
            onSubmit={(e) => {
              e.preventDefault();
              handleSend(inputText);
            }}
            style={{
              padding: "10px 14px",
              background: "var(--surface)",
              borderTop: "1px solid var(--border)",
              display: "flex",
              gap: "8px",
              alignItems: "center"
            }}
          >
            <input
              type="text"
              value={inputText}
              onChange={(e) => setInputText(e.target.value)}
              placeholder="Ask a solar question..."
              style={{
                flex: 1,
                background: "var(--card)",
                border: "1px solid var(--border)",
                color: "var(--text)",
                borderRadius: "8px",
                padding: "8px 12px",
                fontSize: "12px",
                outline: "none",
                transition: "border-color 0.2s"
              }}
            />
            <button
              type="submit"
              disabled={!inputText.trim()}
              style={{
                background: inputText.trim() ? "linear-gradient(135deg, var(--cyan), var(--blue))" : "var(--border)",
                border: "none",
                borderRadius: "8px",
                width: "32px",
                height: "32px",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                cursor: inputText.trim() ? "pointer" : "not-allowed",
                transition: "all 0.2s"
              }}
            >
              <SendIcon size={14} color={inputText.trim() ? "#000000" : "var(--text-dim)"} />
            </button>
          </form>
        </div>
      )}
    </div>
  );
}
